name: Check example

on:
  push:

jobs:
  example:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache bundler gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Cache Mint packages
      id: mint-cache
      uses: actions/cache@v3
      with:
        path: /Users/runner/.mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - name: Bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run example
      run: bundle exec fastlane test
