name: Check example

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundler gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run example
      run: bundle exec fastlane test
